name: test

# 触发条件：手动
on:
  workflow_dispatch
# 任务
jobs:
  set_up:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout
        uses: actions/checkout@v2
      - name: test
        run:
         
         python 1.py
        
